### PR TITLE
Adds ignore prop for statusbar style

### PR DESCRIPTION
**Pull request by EmilScherdin**
Added to be able to use react-native-navbar and style/change the statusbar from other parts of the app.
## Case

I want `react-native-navbar` but want to change the statusbar color based on the background color of the navbar. I could use `react-native-navbar` for this but the problem is when swiping back. Then the statusbar color not changes back. To fix this the simples way is for me to style the statusbar by my self in the renderScene function of `react-native/navigator`. thats way i added a option to ignore styling of the statusbar in this package

### CODE REVIEW

**Comment by Kureev** [comment]
What about passing "default" as a "style" instead of using an additional key?

**Comment by EmilScherdin** [comment]
@Kureev Passing "default" to "style" will just set the statusbar color to black.

I change the navbar color in different views and the navbar does not re-render on swipe back.
So if i have white statusbar color in the root view and the change to black statusbar color in the second view and swipe back the statusbar color would still be black.

**Comment by jukkakoskinen** [comment]
My use case is exactly like @EmilScherdin's. @Kureev, please consider merging this.

**Comment by EmilScherdin** [comment]
@jukkakoskinen My solution was to stop using this and built my own, I wanted to change more and more stuff on this package but it's easier just to do it yourself.

**Comment by jukkakoskinen** [comment]
Cool! Do you have it on GitHub?

**Comment by EmilScherdin** [comment]
@jukkakoskinen Nope, sorry! But just fork your own version of this or fork my pull request 😄

**Pull request closed without merging**
