### PR TITLE
Allow accessibility label for navbar button

### PR DESCRIPTION
**Pull request by robrichard**
Allow consumer to set the `accessible` and `accessibilityLabel`property through the button configs.

### CODE REVIEW

**Comment by Kureev** [comment]
Can you also add it to the README, please (API section)?

**Comment by robrichard** [comment]
@Kureev - the README has been updated. Thanks!

**Comment by Kureev** [comment]
Great! Thank you so much!

**Comment by Kureev** [comment]
Published in 1.7.0

**Pull request merged**
