### PR TITLE
use ViewPropTypes.style instead of View.props.style

### PR DESCRIPTION
**Pull request by nhducit**

### CODE REVIEW

**Comment by Kureev** [comment]
Thanks, @nhducit! 🙌

**Comment by Kureev** [comment]
`1.8.1` has been released with this fix

**Comment by qiangspecial** [comment]
@Kureev  `ViewPropTypes` is support in react-native@^0.44，so if my app dependencies react-native version is lower than 0.44，it will be crash！

**Comment by nhducit** [comment]
@Kureev should we revert this PR and release a new major version

**Comment by Kureev** [comment]
Right, it should've been a major bump. I'll ask `npm` to unpublish 1.8.1

**Comment by Kureev** [comment]
1.8.1 has been unpublished, 2.0.0 has been released

**Pull request merged**
